#!/bin/bash
# shellcheck disable=SC2034  # Unused variables left for readability

Software_Name="Shephard Systems"
# Remove h to fix voice"s mispronunciation.
Software_Name_Spoken="Shepard Systems"
# Ascii art generated from: http://patorjk.com/software/taag/#p=display&f=Slant&t=Project%20Atlas
Software_Name_Ascii="   _____ __               __                   __   _____            __                     
  / ___// /_  ___  ____  / /_  ____ __________/ /  / ___/__  _______/ /____  ____ ___  _____
  \__ \/ __ \/ _ \/ __ \/ __ \/ __ \`/ ___/ __  /   \__ \/ / / / ___/ __/ _ \/ __ \`__ \/ ___/
 ___/ / / / /  __/ /_/ / / / / /_/ / /  / /_/ /   ___/ / /_/ (__  ) /_/  __/ / / / / (__  ) 
/____/_/ /_/\___/ .___/_/ /_/\__,_/_/   \__,_/   /____/\__, /____/\__/\___/_/ /_/ /_/____/  
               /_/                                    /____/                                "
# Line inspired by a Domain monitoring product: https://www.domaintools.com/products/monitoring
# It becomes a little more nefarious when applied to monitoring humans.
Slogan="Find the Wolf, Track the Herd"
Show_Sec=0.03
Email="mbdyson@shephard.net"
Password="DEEelPyEc2Eqf1lRQt5hSw==" # Generated with: $(openssl rand -base64 16)
Voice="Moira"
First_Name="Miles"
Name="$First_Name Bennett Dyson"
Department="AI Maintenance Department"
Region="District 6"
Divider=$(printf %"$COLUMNS"s | tr " " "_")
Prompt=">>>$Email>>> "
Num_Printed_Residents=150
# Names generated from: https://www.fakenamegenerator.com/order.php
Resident_List=("Rose E Morris"
  "Leila C Nathan"
  "Emma S Johnson"
  "Elizabeth M Stockstill"
  "Florida M Scott"
  "Marta J Chavez"
  "Dean T Cole"
  "Brittany C Ball"
  "Roger S Warren"
  "Tiffany V Malave"
  "Patricia H Lander"
  "April I Butt"
  "Rex P Taylor"
  "Mary R Becker"
  "Daniel L Gunn"
  "Jason K Barnett"
  "Erica M Ross"
  "Jennifer P Allen"
  "Suzanne J Pogue"
  "Myra S Busby"
  "Ethel T Kerns"
  "Leroy D Macklin"
  "Jose P Holland"
  "Brandon D Burch"
  "Donald B Lewis"
  "Leonard B Waters"
  "Chassidy K Smith"
  "Robert L Canavan"
  "Barbara B Hernandez"
  "Juan P Munos"
  "Antoinette B Harman"
  "Bernice R Sherman"
  "Helena W Nolan"
  "Nancy P Magana"
  "Beth G Johnson"
  "Cristy T Martin"
  "Shannon J McDuffy"
  "Johanna R Pereira"
  "Richard P Stemple"
  "Maryann M Jordan"
  "Angela E Malcom"
  "Nancy S Schaffner"
  "Irene J Gaines"
  "Chris I Carpenter"
  "Linda T Martin"
  "Terry K Swigert"
  "Lavon T Lewis"
  "Lucien L Boykin"
  "Eddie H Raley"
  "Evelyn R Landry"
  "Don S Martin"
  "Brad J Cisneros"
  "Kevin J Reese"
  "Jaime L Roybal"
  "Maria E French"
  "Una A Rector"
  "Jessica J Pua"
  "Laura K Vargas"
  "Gregory I Hines"
  "Lionel M Kimber"
  "Roy K Halterman"
  "Mary F Howard"
  "James A Reed"
  "Edward C Saul"
  "Nathan M Seger"
  "Richard B Carter"
  "Edward L Conley"
  "Dorothy B Chicoine"
  "Vincent C Milner"
  "Timothy S Thomas"
  "Jose R Groves"
  "David C Dill"
  "Florence G Miller"
  "John M Marquez"
  "Daniel B Anderson"
  "Todd S Weaver"
  "Magdalena E Christian"
  "Lydia R Holbrook"
  "Carol R Zander"
  "Chuck K Robertson"
  "Tana A Wilson"
  "Wallace M Johnson"
  "Kathleen R Reed"
  "Donald M Thigpen"
  "Bonita J Harris"
  "Mark T Smith"
  "Alicia R Bivona"
  "Rebecca M Donovan"
  "Amber J Patten"
  "Frank L Tate"
  "John C Dawson"
  "Lee J Pate"
  "Maria R Santiago"
  "Faustino L Halbert"
  "Jane G Alston"
  "Jose D Moore"
  "Emma C Bennett"
  "Leon J Mitchell"
  "James E Cooper"
  "Allan T Phelps"
  "Morris G McCurry"
  "Frances L Victor"
  "Jennifer S Merz"
  "Alisa J Stephens"
  "Teresa G Poteat"
  "Andrea A Freeman"
  "Elizabeth D Black"
  "Gwendolyn B Worth"
  "Jane J Geary"
  "Joan G Hamlett"
  "Robert R Hildebrand"
  "Donna T Lopez"
  "Rena G White"
  "Flora W Briscoe"
  "Barbara D Scarlett"
  "Cheryl R McManus"
  "Matthew A Nutt"
  "Linda R Baxter"
  "Melissa R Garcia"
  "Byron S Reddick"
  "Daniel L Brainard"
  "Angelina C Gossage"
  "Amanda D Austin"
  "John N Norris"
  "Dennis S Leach"
  "Patricia R Baker"
  "Theodore J Hanson"
  "Christy D Kendricks"
  "Mario L Anderson"
  "Robert S Bigelow"
  "Michael N Harris"
  "Lee P Preslar"
  "Jonathan A Mars"
  "George L Johnson"
  "Henrietta K Schroder"
  "Douglas E Parnell"
  "Rebecca J Rutledge"
  "Mary K Stewart"
  "Cesar K Rios"
  "Dolores D Taylor"
  "Matthew D Ferguson"
  "Francis C Jamison"
  "Lee R Parker"
  "Altha T Stephenson"
  "Richard M Lewis"
  "David M Vera"
  "Aleta B Paige"
  "Walter R Newsom"
  "Shirley S Schmidt"
  "Maxine H Marrs")
